In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from ucimlrepo) (2025.4.26)
Requirement already satisfied: numpy>=1.26.0 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\geeks_pc31\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                               None    cm             no
1                                               None    cm             no
2                                               None    cm             no
3                                               None    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...  None             no

In [4]:
import pandas as pd

df = pd.concat([X, y], axis=1)
df.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
df = df.rename(columns={"class": "species"})

In [7]:
mean_val = df['sepal length'].mean()
median_val = df['sepal length'].median()
variance_val = df['sepal length'].var()

print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)

Mean: 5.843333333333334
Median: 5.8
Variance: 0.6856935123042505

In [9]:
df['petal_length_normalized'] = (
    (df['petal length'] - df['petal length'].min()) /
    (df['petal length'].max() - df['petal length'].min())
)

df[['petal length', 'petal_length_normalized']].head()

   petal length  petal_length_normalized
0           1.4                 0.067797
1           1.4                 0.067797
2           1.3                 0.050847
3           1.5                 0.084746
4           1.4                 0.067797

In [10]:
def linear_search_species(df, target):
    results = []
    for i in range(len(df)):
        if df.iloc[i]['species'] == target:
            results.append(df.iloc[i])
    return results

setosa_rows = linear_search_species(df, "Iris-setosa")
print("Rows found:", len(setosa_rows))

Rows found: 50

In [11]:
df.query("species == 'Iris-setosa'")

,sepal length,sepal width,petal length,petal width,species,petal_length_normalized
0,5.1,3.5,1.4,0.2,Iris-setosa,0.067797
1,4.9,3.0,1.4,0.2,Iris-setosa,0.067797
2,4.7,3.2,1.3,0.2,Iris-setosa,0.050847
3,4.6,3.1,1.5,0.2,Iris-setosa,0.084746
4,5.0,3.6,1.4,0.2,Iris-setosa,0.067797
5,5.4,3.9,1.7,0.4,Iris-setosa,0.118644
6,4.6,3.4,1.4,0.3,Iris-setosa,0.067797
7,5.0,3.4,1.5,0.2,Iris-setosa,0.084746
8,4.4,2.9,1.4,0.2,Iris-setosa,0.067797
9,4.9,3.1,1.5,0.1,Iris-setosa,0.084746
10,5.4,3.7,1.5,0.2,Iris-setosa,0.084746
11,4.8,3.4,1.6,0.2,Iris-setosa,0.101695
12,4.8,3.0,1.4,0.1,Iris-setosa,0.067797
13,4.3,3.0,1.1,0.1,Iris-setosa,0.016949
14,5.8,4.0,1.2,0.2,Iris-setosa,0.033898
15,5.7,4.4,1.5,0.4,Iris-setosa,0.084746
16,5.4,3.9,1.3,0.4,Iris-setosa,0.050847
17,5.1,3.5,1.4,0.3,Iris-setosa,0.067797
18,5.7,3.8,1.7,0.3,Iris-setosa,0.118644
19,5.1,3.8,1.5,0.3,Iris-setosa,0.084746
20,5.4,3.4,1.7,0.2,Iris-setosa,0.118644
21,5.1,3.7,1.5,0.4,Iris-setosa,0.084746
22,4.6,3.6,1.0,0.2,Iris-setosa,0.000000
23,5.1,3.3,1.7,0.5,Iris-setosa,0.118644
24,4.8,3.4,1.9,0.2,Iris-setosa,0.152542
25,5.0,3.0,1.6,0.2,Iris-setosa,0.101695
26,5.0,3.4,1.6,0.4,Iris-setosa,0.101695
27,5.2,3.5,1.5,0.2,Iris-setosa,0.084746
28,5.2,3.4,1.4,0.2,Iris-setosa,0.067797
29,4.7,3.2,1.6,0.2,Iris-setosa,0.101695
30,4.8,3.1,1.6,0.2,Iris-setosa,0.101695
31,5.4,3.4,1.5,0.4,Iris-setosa,0.084746
32,5.2,4.1,1.5,0.1,Iris-setosa,0.084746
33,5.5,4.2,1.4,0.2,Iris-setosa,0.067797
34,4.9,3.1,1.5,0.1,Iris-setosa,0.084746
35,5.0,3.2,1.2,0.2,Iris-setosa,0.033898
36,5.5,3.5,1.3,0.2,Iris-setosa,0.050847
37,4.9,3.1,1.5,0.1,Iris-setosa,0.084746
38,4.4,3.0,1.3,0.2,Iris-setosa,0.050847
39,5.1,3.4,1.5,0.2,Iris-setosa,0.084746
40,5.0,3.5,1.3,0.3,Iris-setosa,0.050847
41,4.5,2.3,1.3,0.3,Iris-setosa,0.050847
42,4.4,3.2,1.3,0.2,Iris-setosa,0.050847
43,5.0,3.5,1.6,0.6,Iris-setosa,0.101695
44,5.1,3.8,1.9,0.4,Iris-setosa,0.152542
45,4.8,3.0,1.4,0.3,Iris-setosa,0.067797
46,5.1,3.8,1.6,0.2,Iris-setosa,0.101695
47,4.6,3.2,1.4,0.2,Iris-setosa,0.067797
48,5.3,3.7,1.5,0.2,Iris-setosa,0.084746
49,5.0,3.3,1.4,0.2,Iris-setosa,0.067797

In [13]:
def bubble_sort_by_sepal(df):
    data = df.to_dict('records')   # convert rows to list of dicts
    n = len(data)

    for i in range(n):
        for j in range(0, n - i - 1):
            if data[j]['sepal length'] > data[j + 1]['sepal length']:
                data[j], data[j + 1] = data[j + 1], data[j]

    return pd.DataFrame(data)

sorted_bubble = bubble_sort_by_sepal(df)
sorted_bubble.head()

,sepal length,sepal width,petal length,petal width,species,petal_length_normalized
0,4.3,3.0,1.1,0.1,Iris-setosa,0.016949
1,4.4,2.9,1.4,0.2,Iris-setosa,0.067797
2,4.4,3.0,1.3,0.2,Iris-setosa,0.050847
3,4.4,3.2,1.3,0.2,Iris-setosa,0.050847
4,4.5,2.3,1.3,0.3,Iris-setosa,0.050847

In [15]:
df_sorted = df.sort_values(by='sepal length')
df_sorted.head()

,sepal length,sepal width,petal length,petal width,species,petal_length_normalized
13,4.3,3.0,1.1,0.1,Iris-setosa,0.016949
8,4.4,2.9,1.4,0.2,Iris-setosa,0.067797
42,4.4,3.2,1.3,0.2,Iris-setosa,0.050847
38,4.4,3.0,1.3,0.2,Iris-setosa,0.050847
41,4.5,2.3,1.3,0.3,Iris-setosa,0.050847